# .gitlab-ci.yml

variables:
  DOCKER_DRIVER: overlay
  IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  HOST_ADDR: 45.32.136.186

stages:
- deploy_to_vultr

deploy_to_vultr:
  stage: deploy_to_vultr
  before_script:
  - . scripts/before_deploy.sh
  script:
  - eval "echo \"$(cat scripts/deploy.sh)\"" | ssh root@$HOST_ADDR 'bash -s'
  only:
  - master
