- name: check if swapfile exists
  stat:
    path: /swapfile
  register: swapfile_stat_result

- name: create swap file
  command: fallocate -l 4G /swapfile
  when: swapfile_stat_result.stat.exists == False

- command: chmod 600 /swapfile
  when: swapfile_stat_result.stat.exists == False

- command: mkswap /swapfile
  when: swapfile_stat_result.stat.exists == False

- command: swapon /swapfile
  when: swapfile_stat_result.stat.exists == False