---
- hosts: all
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
  vars:
    build_mysql_container: false
  roles:
    - { role: './roles/mysql' }
    - { role: './roles/awscli' }
    - { role: './roles/backup' }
