---
- hosts: all
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
  roles:
    - { role: './roles/swapfile' }
    - { role: './roles/install-docker' }
    - { role: './roles/mysql' }
    - { role: './roles/jira' }
